# Generated by Django 4.2.11 on 2024-09-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cation',
            new_name='caption',
        ),
    ]
